import { discoveryCompetitionConfig, discoveryCompetitionWorld, discoveryCompetitionMasses } from '../lib/discovery-competition.ts';
import { generalistGenome, stateHash, PRESETS, presetConfig } from '@bl/schema';
import { toHex } from '../lib/selection-funnel-audit.ts';
const a=generalistGenome(60,20),g=toHex({...a,weights:Array.from(a.weights)}),b=toHex({...a,mu:61,weights:Array.from(a.weights)});
const assert=(x:unknown)=>{if(!x)throw Error('assertion failed')};
Deno.test('full gradient rules unchanged except measurement mutation toggle',()=>{const cfg=discoveryCompetitionConfig(6400001),preset=presetConfig(PRESETS.find(p=>p.id==='gradient-m3')!,6400001);assert(JSON.stringify(cfg)===JSON.stringify({...preset,mutRate:0}))});
Deno.test('all position and label assignments have equal starting material',()=>{const cfg=discoveryCompetitionConfig(6400001);let mass:number|undefined;for(let assignment=0;assignment<4;assignment++){const r=discoveryCompetitionWorld(cfg,g,b,assignment),m=discoveryCompetitionMasses(r.state,r.descendantLineage,r.ancestorLineage);assert(m.descendant>0&&m.descendant===m.ancestor&&m.unexpected===0&&m.unassociated===0);if(mass!==undefined)assert(mass===m.descendant);mass=m.descendant;}});
Deno.test('empty-slot controls preserve active material and assigned lineage',()=>{const cfg=discoveryCompetitionConfig(6400001);for(let assignment=0;assignment<4;assignment++){const pair=discoveryCompetitionWorld(cfg,g,b,assignment),solo=discoveryCompetitionWorld(cfg,g,null,assignment);const p=discoveryCompetitionMasses(pair.state,pair.descendantLineage,pair.ancestorLineage),s=discoveryCompetitionMasses(solo.state,solo.descendantLineage,solo.ancestorLineage);assert(s.ancestor===0&&s.unexpected===0&&s.descendant===p.descendant);assert(solo.descendantLineage===pair.descendantLineage)}});
Deno.test('identical-genome reverse scoring states are exact duplicates, not independent replicates',()=>{const cfg=discoveryCompetitionConfig(6400001),a=discoveryCompetitionWorld(cfg,g,g,0),b=discoveryCompetitionWorld(cfg,g,g,3);assert(stateHash(a.state)===stateHash(b.state));assert(a.descendantLineage===b.ancestorLineage&&a.ancestorLineage===b.descendantLineage)});

Deno.test('malformed ancestor is not converted to an empty competitor',()=>{let rejected=false;try{discoveryCompetitionWorld(discoveryCompetitionConfig(6400001),g,'',0)}catch{rejected=true}assert(rejected)});
