// Generated by tools/retest.ts --founders from experiments/m3/retest.json; do not edit.
//
// The ensemble founder set: the best genome of each M3 genetic cluster that
// passes the M3 test under the later-gate rule (docs/plan.md, "Probability
// gates"): 32 fresh-seed replicates (seeds 2000001..2000050) with survival,
// regeneration after a 30% lesion and death without light each at a one-sided
// 95% lower bound above 0.8.
//
// M3_FOUNDER_SET is the content digest of the set (founderSetId in
// packages/search/src/retest.ts). Presets bind to one set by id: a different
// set needs new preset ids, so runs from different sets are never pooled.
import type { Genome } from "./genome.ts";

export const M3_FOUNDER_SET = "m3-6bdd91c307379d01";

export interface M3Founder {
  /** Genetic cluster in the M3 confirmation (runs/bootstrap-200/confirm.json). */
  cluster: number;
  /** Retest counts out of `reps`. */
  survived: number;
  regenerated: number;
  lightDependent: number;
  reps: number;
  mu: number;
  sigma: number;
  motGain: number;
  /** Controller weights, int8 as two's-complement hex. */
  weights: string;
}

export const M3_FOUNDERS: readonly M3Founder[] = [
  { cluster: 0, survived: 32, regenerated: 30, lightDependent: 32, reps: 32, mu: 59, sigma: 17, motGain: 0, weights: "f6df17d6073cfc3cc40ae72c12f9d3f138d2eb1ce6c9373cecf1d23a441813e604e22efd1a0ad9f3cdf74029260eb5fe063bc0c0daee3a3acc0ecf4010c4c920393b2119fabc2a0e3a391508f12c221a1ffed300d221192b00c8051a020ae30df5c30a02cac00bd403c93b0adb35d6e6e6f9c2fef82a30e7db0aead5e3e225272125472c1af91c053f2118eaf800123b23d429db1e0c090c0ef0e4d0fce4ff31" },
  { cluster: 1, survived: 32, regenerated: 31, lightDependent: 32, reps: 32, mu: 28, sigma: 24, motGain: 0, weights: "05e01d2616e02a372a38e6c4df272a2b20cb21130bebe717f0eef3e9e6e1c73beaeed50c0521f9c8e8c02821263be7e5d73d22e129fcf5f71b041cfe1ef61cc4ff02c619d5d61e29213c32c13538e22520fe21ec312604d3f725e237f431120828f3270cdff4fb243f221f1c29d5f2d1d60d1c15062ec012d12a15f00105dcda2a11de0b13031f260ed32ee2f7efda0e09eef91726f2e30b3fedcbdada352d3d" },
  { cluster: 2, survived: 32, regenerated: 32, lightDependent: 32, reps: 32, mu: 80, sigma: 26, motGain: 0, weights: "d0d0fdd009c3c0fd05da35fcc707d3222a35ef3807df2aca0532e828360110ff290d1dcd33f919d739cdfb163d402b1126cedcff3528fe2d001322fcfbd8e61330e8c6000d0f3937cd3b31ce0fcee5f724cb18283fc501dad7fa25c8023725d53a2315fb16243ff52b3e2013c7fc26fe25c8e5fce637ce372323dd23133f14e1c7ffd6f701d50adf14011ed63609221629c03f213e1cddc9fce33725f1e1f121" },
  { cluster: 4, survived: 32, regenerated: 32, lightDependent: 32, reps: 32, mu: 60, sigma: 20, motGain: 0, weights: "00000000000000000000000000ec0000000000000000000000000000000000007f00000000000000007f000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000081f17f000000006e1800000000000000000000f200000000000000000000000100000000000000000000000000e90000000000000000000000000000000000004628e80c000000" },
  { cluster: 5, survived: 32, regenerated: 32, lightDependent: 32, reps: 32, mu: 42, sigma: 18, motGain: 0, weights: "ede3f2e5242312cafc3035e12f1923f113111cefe0c3312a380de8cfda12d8363c33f932e8fa3bc7da19f7fbff40c4f43e38ecc9dd3512cbf126dc0a15c9e00ecb162bcbf7d6da0dc1d51e3bfa10cadafd1126c9d4112136d50e2feb04f1ce0f0aef37e325fde9de3ee9cbc5cc24263fd21dd2db2503f8f2dd2ddbce2e40f6d4272de1def02af4080ff2fc1b3b09c7e40ff9e6dcc22b173629da052bc6322fd6" },
  { cluster: 9, survived: 32, regenerated: 32, lightDependent: 32, reps: 32, mu: 32, sigma: 26, motGain: 0, weights: "dd30e03b3df431c127c6cdd83d2c13f5de0efa03ed170c3bcd38f6e70d20fde94730da09e4dbef30de25efe0d53a0effd1e8d8d8403bdef7d3d93ecf0afbded11ffeeb16dff52dde0f34f439fbd4fd32f5d324c326e0fed2f007e80dfd3b12070beacafdfdc22a2d2e1df5d1d2f3f1d530f104c234fcf23c29020007df36d410171b21fbced8dcfade1fd1f7f241f2e01202f9e0270534f631171ae9da3accce" },
  { cluster: 10, survived: 32, regenerated: 31, lightDependent: 32, reps: 32, mu: 60, sigma: 20, motGain: 0, weights: "000000000000000000000000000000000000000000000000000000000000fdf47f0000fc00000008e87f0000000000000000fd000000000000000000000000000000000000000100000000000000000000004000000000000081007f000000006e00000000000000000000000000000000000000000000000000000000000000000000000000000013000000000000000000f90018000000004613e80c000000" },
  { cluster: 11, survived: 32, regenerated: 31, lightDependent: 32, reps: 32, mu: 37, sigma: 12, motGain: 0, weights: "f8f6f0c51223112a01d5d0c62807d51d29c721c23530290e26d3fd3e163f350fd13dce1f29fcd527203dca0b1cfb0625c9ead3c538d9db080c1ac5c1d905e632ca40ef16e723e1f8efd7ea39003133c526dd3cd7ef03c42b2835072d2dc8fa2e23de14d9f406f0ef2d2fd7dee70639c02fc514fc21d935ce4015220b3806eb1af125161ee6073a0ef7efc90338efeb08252bcdeed823c70f07fbe20ffcf8d601" },
  { cluster: 12, survived: 32, regenerated: 31, lightDependent: 32, reps: 32, mu: 38, sigma: 25, motGain: 0, weights: "2e15e9fcd427c814fac534c1061c35ee2cde3c0afe13e02336c7d9113ede2b30dc0326cc2f34c427d90e40c8c52504fbe1121507fd06dbf535c6e623d0f6c7c6e9182cf0e21f352f351c3af6d911eac4eccdebd005d6ecdcea23fcf008123ae3d526fbd9d0da1b031f05273fe3c724fcc5c3fe3b38ff1ac614ca2e28e507da3ad9e8e82ffcdacbc00437e428100e3a1ec93bcb111d2bf2c4192dd41ecbd8f230" },
  { cluster: 16, survived: 32, regenerated: 32, lightDependent: 32, reps: 32, mu: 38, sigma: 27, motGain: 0, weights: "fbfe1b2fe53a16d5fac2f5fa272e2c233bc303d4110d1d2eff0cf1cee30b011e19f3fd23143ac41640173b0e14d83d272d3bc5bce0d83de0c6cad426ec3c1fd109cadec6f5cf1bdc1c1fc124aee63503ed34c11334dce3f0003336c02cdfc2da29e4e823d5f73a2ed2cce923dff6301a0f330dc00d0ac12bf6f01f11192c19c103e01c243e0425f92824fc1e3426c6fbfb1bf8fcd923d6091bf11df3e3251728" },
  { cluster: 17, survived: 31, regenerated: 30, lightDependent: 31, reps: 32, mu: 38, sigma: 25, motGain: 0, weights: "2e15e9fcd427c814fac534c1061c35ee2cde3c0afe13e02341c7d9114ede2b30dc0326cc2f34c412d90e40ddc52504fbe1121507fd06d0f535c6e623d0f6c7c6e9182cf0e21f352f351c24f6d911f1c4eccddbd005d6f3dcea23fced08123ae3d51efbd9d0da1b031f05273fe3c724f5c5c3f63b38ff1ac614ca2e28e807e13ad9e8e82ffcdacbc00437e428100e3a1ec93bcb1d1d2bf2c4192dd41ecbd8f230" },
  { cluster: 20, survived: 32, regenerated: 32, lightDependent: 32, reps: 32, mu: 32, sigma: 22, motGain: 0, weights: "dd30f23b3df431c127c6cdd83d2c13f5de0efa03f6170c3bcd38f6e70d20fde93830da09e4dbef30de25efe0d53a0effd1e8d8d8403bdef7d3d93ecf0bfbded11ffeeb16df0326de0f34f439fbd4fd32f5d324cf2de0fed2f007e80dfd3b12070beacafdfdc22a2d2e1df5d1d2f3f1d530f104c234fcf23e18020007df36d410171b21fbb6d8dcfade1fd1f7f237f2e01202f9e0270545f631171ae9da3accce" },
  { cluster: 23, survived: 32, regenerated: 31, lightDependent: 32, reps: 32, mu: 82, sigma: 22, motGain: 0, weights: "221dc907fcf03fead611f6f9310038d00a09c706c036ce3dc4e0f8df2eff2024d9fefa13ccdcf9d40e0bfa2bff2ce9053cf23accea361ce7efffcad6e708c1e214cb30d1260d2ec0fffd15121039090634c82acc17dfcf2eeaf4c23310272beb1be7d2e8ef21c839013703ceda3d25401f2f3ee9c826c226cc2b030dcb0416093cc5f3390a18013ec10af7f1ce3123f727291eceef11c1c128f7c41716cd3d1e" },
];

export function founderGenome(f: M3Founder): Genome {
  const w = new Int8Array(f.weights.length / 2);
  for (let i = 0; i < w.length; i++) w[i] = parseInt(f.weights.slice(2 * i, 2 * i + 2), 16) << 24 >> 24;
  return { mu: f.mu, sigma: f.sigma, motGain: f.motGain, weights: w };
}
