defmodule Coordinator.CheckpointTest do
  use ExUnit.Case, async: true
  alias Coordinator.Checkpoint

  # Builds a structurally valid checkpoint for a 8x8 world at `step`.
  def build(step, opts \\ []) do
    cfg = Jason.encode!(%{"tileW" => 8, "tileH" => 8, "tilesX" => 1, "tilesY" => 1})
    pad = rem(4 - rem(byte_size(cfg), 4), 4)
    n = 64

    head =
      [0x4B434C42, 2, Keyword.get(opts, :rule, 1), step] ++
        [0, 0, 0, Keyword.get(opts, :heat_hi, 0)] ++
        List.duplicate(0, 20) ++ [0, byte_size(cfg)]

    words = fn ws -> for w <- ws, into: <<>>, do: <<w::little-32>> end
    cells = Keyword.get(opts, :cells, n * 7)

    body =
      words.(head) <>
        cfg <>
        :binary.copy(<<0>>, pad) <>
        words.([cells]) <>
        :binary.copy(<<0>>, cells * 4) <> words.([n * 44]) <> :binary.copy(<<0>>, n * 44 * 4)

    {c1, c2} = Checkpoint.digest(body)
    body <> <<c1::little-32, c2::little-32>>
  end

  test "accepts a well-formed checkpoint at the expected step" do
    assert {:ok, _} = Checkpoint.validate(build(500), 500)
  end

  test "computes the canonical state digest exactly as the TypeScript stateHash" do
    # Generated by tools/fixtures/coordinator-checkpoint.ts: step 12, seed 7.
    bin = File.read!(Path.join(__DIR__, "../fixtures/small.blck"))
    assert {:ok, info} = Checkpoint.validate(bin, 12, 7)
    assert Checkpoint.state_digest(info) == "47f52231ebcc260a"
    assert {:error, "config seed" <> _} = Checkpoint.validate(bin, 12, 8)
  end

  test "bytes digest matches bytesDigest" do
    assert Checkpoint.bytes_digest("hello world") == "62027083312a497c"
  end

  test "rejects wrong step, corrupted bytes, empty bodies and bad sections" do
    assert {:error, "end step" <> _} = Checkpoint.validate(build(400), 500)
    bin = build(500)
    <<head::binary-size(200), b, rest::binary>> = bin

    assert {:error, "checksum mismatch"} =
             Checkpoint.validate(head <> <<Bitwise.bxor(b, 1)>> <> rest, 500)

    assert {:error, _} = Checkpoint.validate(<<>>, 500)
    assert {:error, "cell size mismatch"} = Checkpoint.validate(build(500, cells: 10), 500)
    assert {:error, "rule version" <> _} = Checkpoint.validate(build(500, rule: 999), 500)
    assert {:error, "ledger" <> _} = Checkpoint.validate(build(500, heat_hi: 0x80000000), 500)
    assert {:ok, _} = Checkpoint.validate(build(500, heat_hi: 0x7FFFFFFF), 500)
  end

  test "digest matches the TypeScript digestWords reference value" do
    # digestWords(Uint32Array.of(1, 2, 3)) computed in packages/schema.
    assert Checkpoint.digest(<<1::little-32, 2::little-32, 3::little-32>>) ==
             {833_212_837, 3_962_106_462}
  end
end
