defmodule Coordinator.CheckpointTest do
  use ExUnit.Case, async: true
  alias Coordinator.Checkpoint

  # Builds a structurally valid v3 checkpoint for a 8x8 world at `step`, with
  # a trailing observer section (default: an empty JSON object). Pass
  # `seed:` when a caller needs `Checkpoint.validate/3`'s seed check to pass.
  def build(step, opts \\ []) do
    base = %{"tileW" => 8, "tileH" => 8, "tilesX" => 1, "tilesY" => 1}
    base = if seed = opts[:seed], do: Map.put(base, "seed", seed), else: base
    cfg = Jason.encode!(base)
    pad = rem(4 - rem(byte_size(cfg), 4), 4)
    n = 64

    head =
      [0x4B434C42, 3, Keyword.get(opts, :rule, 1), step] ++
        [0, 0, 0, Keyword.get(opts, :heat_hi, 0)] ++
        List.duplicate(0, 20) ++ [0, byte_size(cfg)]

    words = fn ws -> for w <- ws, into: <<>>, do: <<w::little-32>> end
    cells = Keyword.get(opts, :cells, n * 7)
    obs = Keyword.get(opts, :observer, "{}")
    obs_pad = rem(4 - rem(byte_size(obs), 4), 4)

    body =
      words.(head) <>
        cfg <>
        :binary.copy(<<0>>, pad) <>
        words.([cells]) <>
        :binary.copy(<<0>>, cells * 4) <>
        words.([n * 44]) <>
        :binary.copy(<<0>>, n * 44 * 4) <>
        words.([byte_size(obs)]) <> obs <> :binary.copy(<<0>>, obs_pad)

    {c1, c2} = Checkpoint.digest(body)
    body <> <<c1::little-32, c2::little-32>>
  end

  test "accepts a well-formed checkpoint at the expected step" do
    assert {:ok, _} = Checkpoint.validate(build(500), 500)
  end

  test "computes the canonical state digest exactly as the TypeScript stateHash, independent of the observer section" do
    # Generated by tools/fixtures/coordinator-checkpoint.ts: step 12, seed 7.
    bin = File.read!(Path.join(__DIR__, "../fixtures/small.blck"))
    assert {:ok, info} = Checkpoint.validate(bin, 12, 7)
    assert Checkpoint.state_digest(info) == "47f52231ebcc260a"
    assert {:error, "config seed" <> _} = Checkpoint.validate(bin, 12, 8)
  end

  test "computes the artifact digest (state + observer) exactly as the TypeScript artifactDigest" do
    bin = File.read!(Path.join(__DIR__, "../fixtures/small.blck"))
    assert {:ok, info} = Checkpoint.validate(bin, 12, 7)

    assert info.observer == %{
             "step" => 12,
             "settings" => %{"censusEvery" => 100, "deepEvery" => 10, "activityThreshold" => nil},
             "tags" => ["b", "a"],
             "meta" => %{"z" => 1, "a" => 2}
           }

    assert Checkpoint.artifact_digest(info) == "5e48ee0f83ad0c61"
  end

  test "matches the TypeScript artifactDigest bit for bit for a float and array-index-like string keys that a naive port gets wrong" do
    # Generated by tools/fixtures/coordinator-checkpoint.ts: step 5, seed 7.
    # `cx: 0.00001` formats as "0.00001" under JS's Number::toString but as
    # "1.0e-5" under Erlang's own shortest-float format; `"2"`/`"10"` are
    # array-index-like keys, which JS always enumerates in ascending numeric
    # order ("2" before "10") regardless of a lexicographic key sort.
    bin = File.read!(Path.join(__DIR__, "../fixtures/stress.blck"))
    assert {:ok, info} = Checkpoint.validate(bin, 5, 7)

    assert info.observer == %{
             "cx" => 0.00001,
             "2" => "b",
             "10" => "a",
             "nested" => %{"5" => 1, "1" => 2, "z" => 3},
             "list" => [3, 1, 2],
             "big" => 1.0e21,
             "neg" => -0.0001
           }

    assert Checkpoint.state_digest(info) == "fd0b0518cb20e952"
    assert Checkpoint.artifact_digest(info) == "47ae68f9daeab443"
  end

  test "an empty observer object round-trips (a default `encodeCheckpoint(state)` call)" do
    assert {:ok, info} = Checkpoint.validate(build(500), 500)
    assert info.observer == %{}
    assert Checkpoint.artifact_digest(info) != Checkpoint.state_digest(info)
  end

  test "rejects a malformed or non-object observer section" do
    assert {:error, "observer section is not valid JSON"} =
             Checkpoint.validate(build(500, observer: "not json"), 500)

    assert {:error, "observer section is not an object"} =
             Checkpoint.validate(build(500, observer: "[]"), 500)
  end

  test "rejects wrong step, corrupted bytes, empty bodies and bad sections" do
    assert {:error, "end step" <> _} = Checkpoint.validate(build(400), 500)
    bin = build(500)
    <<head::binary-size(200), b, rest::binary>> = bin

    assert {:error, "checksum mismatch"} =
             Checkpoint.validate(head <> <<Bitwise.bxor(b, 1)>> <> rest, 500)

    assert {:error, _} = Checkpoint.validate(<<>>, 500)
    assert {:error, "cell size mismatch"} = Checkpoint.validate(build(500, cells: 10), 500)
    assert {:error, "rule version" <> _} = Checkpoint.validate(build(500, rule: 999), 500)
    assert {:error, "ledger" <> _} = Checkpoint.validate(build(500, heat_hi: 0x80000000), 500)
    assert {:ok, _} = Checkpoint.validate(build(500, heat_hi: 0x7FFFFFFF), 500)
  end

  test "digest matches the TypeScript digestWords reference value" do
    # digestWords(Uint32Array.of(1, 2, 3)) computed in packages/schema.
    assert Checkpoint.digest(<<1::little-32, 2::little-32, 3::little-32>>) ==
             {833_212_837, 3_962_106_462}
  end

  test "canonical JSON matches JSON.stringify for non-ASCII keys and escaped strings" do
    # Generated by tools/fixtures/coordinator-checkpoint.ts (unicode.blck).
    bin = File.read!(Path.join(__DIR__, "../fixtures/unicode.blck"))
    assert {:ok, info} = Checkpoint.validate(bin, 3, 7)
    assert Checkpoint.state_digest(info) == "1510f164c70c991a"
    assert Checkpoint.artifact_digest(info) == "f61760ad351f4e4c"
  end
end
